<template>
  <InventorySectionShell :title="isNew ? 'سفارش خرید جدید' : order?.name || 'جزئیات سفارش خرید'" subtitle="اقلام خرید، نرخ‌ها و دریافت مرحله‌ای">
    <template #actions><button type="button" class="secondary-btn" @click="goBack">بازگشت به لیست خرید</button></template>
    <p v-if="error" class="error">{{ error }}</p><p v-if="message" class="success">{{ message }}</p>
    <ManagementSurfaceCard v-if="isNew || editing" title="فرم سفارش خرید" subtitle="مقدار و نرخ هر قلم را ریز به ریز ثبت کنید.">
      <div class="form-grid"><label>تأمین‌کننده<select class="input" v-model="form.supplier"><option value="">بدون تأمین‌کننده</option><option v-for="supplier in boot?.suppliers||[]" :key="supplier.name" :value="supplier.name">{{ supplier.supplier_name||supplier.name }}</option></select></label><label>انبار مقصد<select class="input" v-model="form.target_warehouse"><option value="">انتخاب انبار</option><option v-for="warehouse in boot?.leaf_warehouses||[]" :key="warehouse" :value="warehouse">{{ warehouse }}</option></select></label><label>تاریخ سفارش<PersianDateInput v-model="form.posting_date" /></label><label>تاریخ تحویل<PersianDateInput v-model="form.expected_date" /></label><label class="full">یادداشت<textarea class="input" rows="2" v-model.trim="form.note"></textarea></label></div>
      <div class="purchase-lines"><header><strong>اقلام خرید</strong><button type="button" class="secondary-btn" @click="addLine">+ افزودن قلم</button></header><div v-for="(line,index) in form.items" :key="index" class="purchase-line"><SearchableDropdown v-model="line.item_code" :options="materialOptions" placeholder="انتخاب ماده..." search-placeholder="جستجو..." @update:model-value="syncLine(line,$event)" /><div class="uom"><small>واحد</small><strong>{{ line.uom||'—' }}</strong></div><input class="input" type="number" min="0.001" step="0.001" v-model.number="line.qty" placeholder="مقدار" /><input class="input" type="number" min="0" v-model.number="line.rate" placeholder="نرخ" /><button type="button" class="tertiary-btn danger" @click="removeLine(index)" :disabled="form.items.length===1">حذف</button></div></div>
      <footer class="actions"><button type="button" class="primary-btn" @click="save" :disabled="saving">{{ saving?'در حال ذخیره...':'ذخیره پیش‌نویس' }}</button></footer>
    </ManagementSurfaceCard>

    <template v-else-if="order">
      <ManagementSurfaceCard title="خلاصه سفارش خرید" subtitle="وضعیت سفارش و دریافت واقعی انبار">
        <div class="detail-meta"><div><small>تأمین‌کننده</small><strong>{{ order.supplier_name||'—' }}</strong></div><div><small>وضعیت</small><strong :class="statusClass(order.status)">{{ order.status }}</strong></div><div><small>تاریخ سفارش</small><strong>{{ order.posting_date }}</strong></div><div><small>درصد دریافت</small><strong>{{ qty(order.received_pct) }}٪</strong></div><div><small>مبلغ کل</small><strong>{{ money(order.grand_total) }}</strong></div></div>
        <div class="table-wrap"><table class="data-table"><thead><tr><th>قلم</th><th>سفارش</th><th>دریافت</th><th>باقی‌مانده</th><th>نرخ</th><th>مبلغ</th><th v-if="canReceive">دریافت این نوبت</th></tr></thead><tbody><tr v-for="line in order.items" :key="line.idx"><td><strong>{{ line.item_name }}</strong><small>{{ line.item_code }}</small></td><td>{{ qty(line.qty) }} {{ line.uom }}</td><td>{{ qty(line.received_qty) }}</td><td :class="line.remaining_qty>0?'warning':'success'">{{ qty(line.remaining_qty) }}</td><td>{{ money(line.rate) }}</td><td>{{ money(line.amount) }}</td><td v-if="canReceive"><input class="input compact" type="number" min="0" step="0.001" :max="line.remaining_qty" v-model.number="receiveLines[line.item_code]" :disabled="line.remaining_qty<=0" /></td></tr></tbody></table></div>
        <div v-if="canReceive" class="receive-box"><label>انبار دریافت<select class="input" v-model="receiveWarehouse"><option v-for="warehouse in boot?.leaf_warehouses||[]" :key="warehouse" :value="warehouse">{{ warehouse }}</option></select></label><button type="button" class="primary-btn" @click="receive" :disabled="receiving">{{ receiving?'در حال ثبت...':'ثبت دریافت' }}</button></div>
        <footer class="actions"><button v-if="order.status==='پیش‌نویس'" type="button" class="secondary-btn" @click="editing=true">ویرایش اقلام</button><button v-if="order.status==='پیش‌نویس'" type="button" class="primary-btn" @click="changeStatus('ارسال‌شده')">ارسال به تأمین‌کننده</button><button v-if="['پیش‌نویس','ارسال‌شده'].includes(order.status)" type="button" class="tertiary-btn danger" @click="changeStatus('لغوشده')">لغو سفارش</button><button type="button" class="secondary-btn" @click="print">چاپ فیش</button></footer>
        <p v-if="order.receipts?.length" class="sub">اسناد دریافت: {{ order.receipts.join('، ') }}</p>
      </ManagementSurfaceCard>
    </template>
  </InventorySectionShell>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import InventorySectionShell from '@/components/management/inventory/InventorySectionShell.vue'
import ManagementSurfaceCard from '@/components/management/ManagementSurfaceCard.vue'
import PersianDateInput from '@/components/PersianDateInput.vue'
import SearchableDropdown from '@/components/SearchableDropdown.vue'
import { getManagementInventoryBoot, getManagementInventoryPurchasePrint, getManagementPurchaseOrder, listManagementRawMaterials, receiveManagementPurchaseOrder, saveManagementPurchaseOrder, updateManagementPurchaseOrderStatus } from '@/utils/api'
import { formatMoney } from '@/utils/format'
const params=new URLSearchParams(window.location.search), orderName=params.get('name')||'', isNew=params.get('new')==='1'||!orderName
const order=ref(null),boot=ref(null),editing=ref(isNew),loading=ref(false),saving=ref(false),receiving=ref(false),error=ref(''),message=ref(''),receiveLines=reactive({}),receiveWarehouse=ref('')
const form=reactive({name:'',supplier:'',target_warehouse:'',posting_date:today(),expected_date:'',note:'',items:[{item_code:'',qty:1,uom:'',rate:0}]})
const materialOptions=computed(()=> (boot.value?.materials||[]).map((item)=>({value:item.name,label:`${item.item_name||item.name} (${item.name})`})))
const canReceive=computed(()=>order.value&&['ارسال‌شده','دریافت جزئی'].includes(order.value.status))
function today(){return new Date().toISOString().slice(0,10)};function qty(v){return Number(v||0).toLocaleString('fa-IR',{maximumFractionDigits:3})};function money(v){return formatMoney(Number(v||0),'IRR')};function statusClass(v){return v==='دریافت کامل'?'success':v==='لغوشده'?'danger':'primary'};function goBack(){window.location.href='/management/inventory/purchases'}
function addLine(){form.items.push({item_code:'',qty:1,uom:'',rate:0})};function removeLine(i){if(form.items.length>1)form.items.splice(i,1)};function syncLine(line,code=line.item_code){line.item_code=code;const meta=(boot.value?.materials||[]).find((item)=>item.name===code);if(meta)line.uom=meta.stock_uom||'Nos'}
function apply(value){order.value=value;editing.value=false;Object.assign(form,{name:value.name,supplier:value.supplier||'',target_warehouse:value.target_warehouse||'',posting_date:value.posting_date||today(),expected_date:value.expected_date||'',note:value.note||'',items:(value.items||[]).map((line)=>({...line}))});Object.keys(receiveLines).forEach((key)=>delete receiveLines[key]);(value.items||[]).forEach((line)=>{receiveLines[line.item_code]=0});receiveWarehouse.value=value.target_warehouse||boot.value?.settings?.default_warehouse||''}
async function load(){loading.value=true;error.value='';try{const [b,m]=await Promise.all([getManagementInventoryBoot(),listManagementRawMaterials({limit:500})]);boot.value={...b,materials:m.items||[]};if(!isNew){const p=await getManagementPurchaseOrder(orderName);apply(p.order)}}catch(err){error.value=err.message||'دریافت سفارش خرید ناموفق بود.'}finally{loading.value=false}}
async function save(){saving.value=true;error.value='';try{const items=form.items.filter((line)=>line.item_code&&Number(line.qty)>0);if(!items.length)throw new Error('حداقل یک قلم معتبر لازم است.');const p=await saveManagementPurchaseOrder({...form,items});window.location.href=`/management/inventory/purchases/detail?name=${encodeURIComponent(p.order.name)}`}catch(err){error.value=err.message||'ذخیره خرید ناموفق بود.'}finally{saving.value=false}}
async function changeStatus(status){try{const p=await updateManagementPurchaseOrderStatus({name:order.value.name,status});apply(p.order);message.value='وضعیت سفارش به‌روزرسانی شد.'}catch(err){error.value=err.message||'تغییر وضعیت سفارش ناموفق بود.'}}
async function receive(){receiving.value=true;error.value='';try{const lines=order.value.items.map((line)=>({item_code:line.item_code,qty:Number(receiveLines[line.item_code]||0)})).filter((line)=>line.qty>0);if(!lines.length)throw new Error('مقدار دریافت را وارد کنید.');const p=await receiveManagementPurchaseOrder({name:order.value.name,warehouse:receiveWarehouse.value,lines});apply(p.order);message.value='دریافت خرید در انبار ثبت شد.'}catch(err){error.value=err.message||'ثبت دریافت ناموفق بود.'}finally{receiving.value=false}}
async function print(){try{const p=await getManagementInventoryPurchasePrint(order.value.name);const w=window.open('','_blank','width=420,height=760');if(!w)throw new Error('پنجره چاپ باز نشد.');w.document.write(`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>${p.name}</title></head><body>${p.html}</body></html>`);w.document.close();w.focus();window.setTimeout(()=>w.print(),300)}catch(err){error.value=err.message||'چاپ ناموفق بود.'}}
onMounted(load)
</script>

<style scoped>
.form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:.65rem}.form-grid label{display:grid;gap:.25rem;font-size:.78rem;color:var(--mg-text-main)}.full{grid-column:1/-1}.purchase-lines{display:grid;gap:.55rem;margin-top:1rem;padding:.8rem;border:1px dashed var(--mg-border);border-radius:15px}.purchase-lines header{display:flex;justify-content:space-between;gap:.5rem}.purchase-line{display:grid;grid-template-columns:minmax(0,3fr) 90px minmax(90px,1fr) minmax(100px,1fr) auto;gap:.45rem;align-items:center}.uom{min-height:38px;display:grid;align-content:center;gap:.1rem;padding:.25rem .45rem;border:1px solid var(--mg-border-light);border-radius:9px}.uom small,.detail-meta small,.sub{color:var(--mg-text-muted);font-size:.68rem}.detail-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:.55rem}.detail-meta>div{display:grid;gap:.18rem;padding:.6rem;border-radius:12px;background:var(--mg-bg-page)}.detail-meta strong{font-size:.8rem}.table-wrap{overflow-x:auto;margin-top:1rem}.data-table{width:100%;border-collapse:collapse}.data-table th,.data-table td{text-align:right;padding:.5rem;border-bottom:1px solid var(--mg-border-light);vertical-align:top;white-space:nowrap}.data-table td small{display:block;color:var(--mg-text-muted);font-size:.67rem}.success{color:var(--mg-success)}.danger{color:var(--mg-danger)}.primary{color:var(--mg-primary)}.warning{color:var(--mg-danger)}.actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:.5rem;margin-top:1rem;padding-top:.7rem;border-top:1px solid var(--mg-border-light)}.receive-box{display:flex;align-items:end;gap:.6rem;margin-top:1rem}.receive-box label{display:grid;gap:.25rem;flex:1;font-size:.78rem}.sub{display:block;margin-top:.5rem}@media(max-width:700px){.purchase-line{grid-template-columns:1fr 1fr}.purchase-line :deep(.search-dropdown){grid-column:1/-1}.purchase-line .uom{min-height:38px}.actions>*{flex:1 1 100%}.receive-box{display:grid;align-items:stretch}.receive-box .primary-btn{width:100%}}
</style>
