import {
  AlertCircle,
  CheckCircle2,
  CircleHelp,
  Clock3,
  Heart,
  Layers3,
  List,
  Package,
  Palette,
  Plus,
  ReceiptText,
  Search,
  Settings2,
  ShoppingCart,
  Sparkles,
  Truck,
  UtensilsCrossed,
  UsersRound,
} from 'lucide-vue-next'

export const designSystemTabs = Object.freeze([
  { id: 'theme', label: 'تم و توکن‌ها', caption: 'رنگ، تایپوگرافی و ریتم' },
  { id: 'icons', label: 'آیکون‌ها', caption: 'خانواده و اندازه‌ها' },
  { id: 'components', label: 'کامپوننت‌ها', caption: 'قطعات قابل استفاده' },
  { id: 'patterns', label: 'پترن‌ها', caption: 'الگوهای عملیاتی' },
  { id: 'templates', label: 'تمپلیت‌ها', caption: 'صفحه‌های مرجع' },
])

export const iconCatalog = Object.freeze([
  { name: 'Search', label: 'جستجو', component: Search, token: 'icon-md' },
  { name: 'Plus', label: 'افزودن', component: Plus, token: 'icon-md' },
  { name: 'Package', label: 'محصول', component: Package, token: 'icon-md' },
  { name: 'UtensilsCrossed', label: 'رستوران', component: UtensilsCrossed, token: 'icon-lg' },
  { name: 'ShoppingCart', label: 'سبد خرید', component: ShoppingCart, token: 'icon-md' },
  { name: 'Heart', label: 'علاقه‌مندی', component: Heart, token: 'icon-md' },
  { name: 'Layers3', label: 'فرمول و لایه‌ها', component: Layers3, token: 'icon-md' },
  { name: 'List', label: 'فهرست داده', component: List, token: 'icon-md' },
  { name: 'ReceiptText', label: 'سفارش و سند', component: ReceiptText, token: 'icon-md' },
  { name: 'Truck', label: 'پیک و ارسال', component: Truck, token: 'icon-md' },
  { name: 'UsersRound', label: 'کاربران و نفرات', component: UsersRound, token: 'icon-md' },
  { name: 'Palette', label: 'تم و رنگ', component: Palette, token: 'icon-md' },
  { name: 'Settings2', label: 'تنظیمات', component: Settings2, token: 'icon-md' },
  { name: 'Sparkles', label: 'ویژه', component: Sparkles, token: 'icon-md' },
  { name: 'Clock3', label: 'زمان آماده‌سازی', component: Clock3, token: 'icon-sm' },
  { name: 'CheckCircle2', label: 'آماده / موفق', component: CheckCircle2, token: 'icon-md' },
  { name: 'AlertCircle', label: 'هشدار', component: AlertCircle, token: 'icon-md' },
  { name: 'CircleHelp', label: 'راهنما', component: CircleHelp, token: 'icon-md' },
])

export const designSystemCatalog = Object.freeze({
  components: Object.freeze([
    { id: 'button', title: 'دکمه‌ها', description: 'عمل اصلی، ثانویه، کم‌اهمیت و خطرناک با حالت‌های focus و loading.', kind: 'primitive' },
    { id: 'surface', title: 'سطح و کارت', description: 'سطوح مدیریت با hierarchy مشخص و بدون تزئین اضافه.', kind: 'primitive' },
    { id: 'status', title: 'Badge و وضعیت', description: 'وضعیت موجودی، انتشار، خطا و موفقیت با متن و رنگ معنایی.', kind: 'primitive' },
    { id: 'product-card', title: 'کارت محصول', description: 'مرجع نمایش محصول در منوی مشتری با image، قیمت و اقدام.', source: 'components/MenuProductCard.vue', kind: 'reference' },
    { id: 'product-detail', title: 'جزئیات محصول', description: 'هدر، رسانه، قیمت، وضعیت، تغذیه و تنظیمات محصول.', source: 'pages/management/ManagementProductDetailPage.vue', kind: 'reference' },
    { id: 'readiness', title: 'آمادگی محصول', description: 'چک‌لیست تکمیل محصول قبل از انتشار در منو.', source: 'components/management/ManagementProductReadinessPanel.vue', kind: 'domain' },
    { id: 'management-list', title: 'فهرست مدیریتی', description: 'جدول واکنش‌گرا با حالت خالی، انتخاب سطر و نمایش موبایل.', source: 'components/management/ManagementListView.vue', kind: 'domain' },
  ]),
  patterns: Object.freeze([
    { id: 'product-search', title: 'جستجو و ایجاد محصول', description: 'جستجوی سروری، فیلتر سریع، نماهای ذخیره‌شده و اقدام ایجاد.' },
    { id: 'product-collection', title: 'مجموعه محصولات', description: 'لیست، گالری، کانبان، شیت، تقویم، درخت و بارگذاری صفحه‌ای.' },
    { id: 'product-availability', title: 'وضعیت فروش', description: 'فعال، به‌زودی، ناموجود و اتمام با مسیر اصلاح واضح.' },
    { id: 'product-detail-sections', title: 'بخش‌بندی جزئیات', description: 'تب‌های اطلاعات، رسانه، قیمت، BOM، صفت‌ها، گزارش و فعالیت.' },
    { id: 'management-list-detail', title: 'فهرست به جزئیات', description: 'انتخاب یک رکورد از فهرست و نمایش جزئیات و عملیات همان رکورد در کنار آن.' },
    { id: 'order-fulfillment', title: 'چرخه سفارش', description: 'فهرست سفارش، جزئیات انتخاب‌شده، پرداخت، تکمیل و تخصیص پیک با متن وضعیت فارسی.' },
    { id: 'courier-workbench', title: 'میزکار پیک', description: 'فهرست پیک‌ها، فرم جزئیات، وضعیت عملیاتی و اتصال به ناوگان.' },
    { id: 'reservation-workbench', title: 'میزکار رزرواسیون', description: 'فیلتر رزرو، فهرست واکنش‌گرا، ویرایش سریع و چرخه تأیید/نشست/لغو.' },
    { id: 'survey-feedback', title: 'بازخورد نظرسنجی', description: 'مدیریت سؤال‌ها و پاسخ‌ها با هشدار نارضایتی و فیلتر بازه و امتیاز.' },
    { id: 'crm-engagement', title: 'تعامل با مشتری', description: 'صدای مشتری و سوابق پیامک با وضعیت فارسی، پاسخ‌دهی و بازخورد عملیات.' },
    { id: 'branch-workbench', title: 'میزکار شعب', description: 'شاخص‌های شعب، فهرست عملکرد، وضعیت فعال و انتقال مشتری بین شعب.' },
    { id: 'cost-control', title: 'کنترل هزینه', description: 'سود و زیان ماهانه، جمع سال، بودجه‌بندی و محاسبه بازگشت سرمایه.' },
    { id: 'accounting-workbench', title: 'میزکار حسابداری', description: 'تراز دریافت و پرداخت، روش‌های پرداخت، مودیان و اسناد اخیر در یک shell.' },
    { id: 'erpnext-master-list', title: 'فهرست مرجع ERPNext', description: 'نمایش و ویرایش داده‌های مرجع ERPNext با همان فهرست مدیریتی، بدون کپی‌کردن DocType.' },
    { id: 'async-feedback', title: 'بازخورد عملیات', description: 'بارگذاری، خطا، موفقیت و retry در همان context عملیاتی.' },
  ]),
  templates: Object.freeze([
    { id: 'products-list', title: 'تمپلیت مدیریت محصولات', description: 'صفحه مرجع برای جستجو، نماها و مدیریت جمعی.', source: 'pages/management/ManagementProductsPage.vue', href: '/management/products' },
    { id: 'product-detail-editor', title: 'تمپلیت ویرایش محصول', description: 'جزئیات کامل یک محصول و مسیر آماده‌سازی آن.', source: 'pages/management/ManagementProductDetailPage.vue', href: '/management/product' },
    { id: 'management-orders', title: 'تمپلیت مدیریت سفارش‌ها', description: 'فهرست سفارش‌ها با جزئیات، پرداخت، تکمیل و تخصیص پیک.', source: 'pages/management/ManagementOrdersPage.vue', href: '/management/orders' },
    { id: 'management-couriers', title: 'تمپلیت مدیریت پیک‌ها', description: 'فهرست پیک و فرم جزئیات در الگوی میزکار محصول‌محور.', source: 'pages/management/ManagementCouriersPage.vue', href: '/management/couriers' },
    { id: 'management-reservations', title: 'تمپلیت مدیریت رزرواسیون', description: 'فهرست رزروهای آنلاین و تلفنی با فیلتر و چرخه وضعیت.', source: 'pages/management/ManagementReservationsPage.vue', href: '/management/reservations' },
    { id: 'management-surveys', title: 'تمپلیت مدیریت نظرسنجی', description: 'سؤال‌های قابل تنظیم و پاسخ‌های مشتری با هشدار نارضایتی.', source: 'pages/management/ManagementSurveysPage.vue', href: '/management/surveys' },
    { id: 'management-club', title: 'تمپلیت باشگاه مشتریان', description: 'مشتریان، صدای مشتری، پیامک و تعامل وفاداری در shell مشترک.', source: 'pages/management/ManagementClubPage.vue', href: '/management/club' },
    { id: 'management-branches', title: 'تمپلیت مدیریت شعب', description: 'فهرست عملکرد شعب با ویرایش، فعال‌سازی و انتقال مشتری.', source: 'pages/management/ManagementBranchesPage.vue', href: '/management/branches' },
    { id: 'management-cost-control', title: 'تمپلیت کنترل هزینه', description: 'سود و زیان، بودجه و ROI با اعداد مالی خوانا و واکنش‌گرا.', source: 'pages/management/ManagementCostControlPage.vue', href: '/management/cost-control' },
    { id: 'management-accounting', title: 'تمپلیت حسابداری', description: 'تراز مالی، تطبیق مودیان و اسناد اخیر با فهرست‌های واکنش‌گرا.', source: 'pages/management/ManagementAccountingPage.vue', href: '/management/accounting' },
    { id: 'erpnext-attribute-catalog', title: 'تمپلیت کاتالوگ صفت ERPNext', description: 'فهرست Item Attribute و ویرایشگر آن در مسیر ساخت variant.', source: 'pages/management/ManagementVariantBuilderPage.vue', href: '/management/product?variant_studio=1' },
    { id: 'public-menu-card', title: 'تمپلیت کارت منوی مشتری', description: 'نمای محصول برای کشف، انتخاب و افزودن به سبد.', source: 'components/MenuProductCard.vue', href: '/menu' },
    { id: 'public-product-detail', title: 'تمپلیت جزئیات مشتری', description: 'گالری، تغذیه، سفارشی‌سازی و اقدام خرید.', source: 'pages/ItemDetailPage.vue', href: '/item' },
  ]),
})
