<template><div class="blog-page" dir="rtl"><section class="blog-hero"><span>مجلهٔ {{ branding.name }}</span><h1>قصه‌ها، طعم‌ها و ایده‌های تازه</h1><p>از مواد اولیه و روش آماده‌سازی تا پیشنهادهایی برای انتخاب خوش‌طعم بعدی.</p><a href="#blog-list">دیدن مقاله‌ها <ArrowDown :size="17" /></a></section><main id="blog-list" class="blog-main"><div class="blog-filters" v-if="categories.length"><button :class="{active:!selected}" @click="selectCategory('')">همه</button><button v-for="category in categories" :key="category" :class="{active:selected===category}" @click="selectCategory(category)">{{ category }}</button></div><p v-if="loading" class="blog-state">در حال بارگذاری مقاله‌ها...</p><div v-else-if="posts.length" class="blog-grid"><a v-for="post in posts" :key="post.name" :href="`/blog/${encodeURIComponent(post.route)}`" class="blog-card"><img v-if="post.cover_image" :src="post.cover_image" :alt="post.title" loading="lazy"><div v-else class="blog-card__placeholder">{{ branding.name.slice(0,1) }}</div><div class="blog-card__body"><small>{{ post.category || 'مجله' }} <span>·</span> {{ post.read_time }} دقیقه مطالعه</small><h2>{{ post.title }}</h2><p>{{ post.excerpt }}</p><b>خواندن مقاله <ArrowLeft :size="16" /></b></div></a></div><div v-else class="blog-state">هنوز مقاله‌ای در این دسته منتشر نشده است.</div></main></div></template>
<script setup>
import { onMounted, ref } from 'vue'
import { ArrowDown, ArrowLeft } from 'lucide-vue-next'
import { getPublicBlogPosts } from '@/utils/api'
import { resolveBranding } from '@/utils/siteComponents'
const props=defineProps({boot:{type:Object,default:()=>({})}});const branding=resolveBranding(props.boot);const posts=ref([]),categories=ref([]),selected=ref(''),loading=ref(true)
async function load(){loading.value=true;try{const r=await getPublicBlogPosts({limit:48,category:selected.value||undefined});posts.value=r?.posts||[];categories.value=r?.categories||[]}catch{posts.value=[]}finally{loading.value=false}}
function selectCategory(v){selected.value=v;load()}
onMounted(load)
</script>
<style scoped>
.blog-page{background:var(--ds-color-surface, #fff);color:var(--ds-color-text-primary);min-height:65vh}.blog-hero{padding:clamp(2.5rem,7vw,5.5rem) 1rem;text-align:center;background:linear-gradient(135deg,color-mix(in srgb,var(--ds-color-action-primary) 10%,var(--ds-color-surface-raised)),color-mix(in srgb,var(--ds-color-action-accent) 9%,var(--ds-color-surface-raised)));border-bottom:1px solid var(--ds-color-border)}.blog-hero span{color:var(--ds-color-action-accent);font-weight:900;font-size:.85rem}.blog-hero h1{max-width:800px;margin:.7rem auto;font-size:clamp(1.8rem,5vw,3.5rem);line-height:1.35}.blog-hero p{max-width:620px;margin:0 auto 1.25rem;color:var(--ds-color-text-secondary);line-height:1.9}.blog-hero a,.blog-card b{display:inline-flex;align-items:center;gap:.45rem;color:var(--ds-color-action-primary);font-weight:900;text-decoration:none}.blog-main{max-width:1200px;margin:auto;padding:2rem 1rem 4rem}.blog-filters{display:flex;gap:.5rem;overflow:auto;padding:.2rem 0 1rem}.blog-filters button{white-space:nowrap;min-height:42px;padding:.5rem .9rem;border:1px solid var(--ds-color-border);border-radius:999px;background:var(--ds-color-surface-raised);color:var(--ds-color-text-secondary);font:inherit;cursor:pointer}.blog-filters button.active{background:var(--ds-color-action-primary);border-color:var(--ds-color-action-primary);color:var(--ds-color-action-primary-foreground,#fff)}.blog-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.blog-card{overflow:hidden;border:1px solid var(--ds-color-border);border-radius:var(--ds-radius-lg);background:var(--ds-color-surface-raised);text-decoration:none;color:inherit;box-shadow:var(--ds-shadow-sm);transition:transform .18s}.blog-card:hover{transform:translateY(-3px)}.blog-card img,.blog-card__placeholder{width:100%;height:220px;object-fit:cover;background:var(--ds-color-surface-muted)}.blog-card__placeholder{display:grid;place-items:center;color:var(--ds-color-action-primary);font-size:4rem;font-weight:900}.blog-card__body{padding:1.1rem}.blog-card small{color:var(--ds-color-action-accent);font-weight:800}.blog-card small span{padding:0 .25rem;color:var(--ds-color-text-muted)}.blog-card h2{margin:.55rem 0;font-size:1.15rem;line-height:1.6}.blog-card p{min-height:3.2em;margin:0 0 .9rem;color:var(--ds-color-text-secondary);line-height:1.8;font-size:.9rem;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.blog-state{padding:3rem 1rem;text-align:center;color:var(--ds-color-text-secondary)}@media(max-width:800px){.blog-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.blog-grid{grid-template-columns:1fr}.blog-card img,.blog-card__placeholder{height:200px}}
</style>
