<template><article v-if="post" class="article-page" dir="rtl"><div class="article-hero"><a href="/blog" class="back"><ArrowRight :size="16"/> بازگشت به مجله</a><div class="article-meta"><span>{{ post.category || 'مجله' }}</span><i>·</i>{{ post.read_time }} دقیقه مطالعه</div><h1>{{ post.title }}</h1><p>{{ post.excerpt }}</p><img v-if="post.cover_image" class="article-cover" :src="post.cover_image" :alt="post.title"></div><div class="article-layout"><div class="article-body" v-html="post.body_html"></div><aside v-if="post.related_products?.length" class="article-products"><h2>محصولات این مقاله</h2><a v-for="item in post.related_products" :key="item.item_code" :href="item.url" class="article-product"><img v-if="item.image" :src="item.image" :alt="item.title"><span v-else class="product-placeholder"><ShoppingBag :size="22"/></span><span><b>{{ item.title }}</b><small>{{ item.note || 'دیدن جزئیات محصول' }}</small></span><ArrowLeft :size="17"/></a></aside></div></article><div v-else class="article-state" dir="rtl">{{ loading?'در حال دریافت مقاله...':'این مقاله پیدا نشد.' }} <a href="/blog">بازگشت به مجله</a></div></template>
<script setup>
import { onMounted,ref } from 'vue'
import { ArrowLeft,ArrowRight,ShoppingBag } from 'lucide-vue-next'
import { getPublicBlogPost } from '@/utils/api'
const post=ref(null),loading=ref(true)
onMounted(async()=>{const route=decodeURIComponent(location.pathname.replace(/^\/blog\/?/,''));try{post.value=(await getPublicBlogPost({route}))?.post||null}catch{post.value=null}finally{loading.value=false}})
</script>
<style scoped>
.article-page{max-width:1080px;margin:auto;padding:1.5rem 1rem 4rem;color:var(--ds-color-text-primary)}.article-hero{max-width:850px;margin:auto}.back{display:inline-flex;align-items:center;gap:.35rem;color:var(--ds-color-action-primary);text-decoration:none;font-weight:800;font-size:.87rem}.article-meta{display:flex;gap:.5rem;margin-top:1.6rem;color:var(--ds-color-text-secondary);font-size:.85rem}.article-meta span{color:var(--ds-color-action-accent);font-weight:900}.article-hero h1{font-size:clamp(1.8rem,5vw,3.35rem);line-height:1.4;margin:.6rem 0}.article-hero>p{color:var(--ds-color-text-secondary);font-size:1.05rem;line-height:1.9}.article-cover{width:100%;max-height:500px;object-fit:cover;border-radius:var(--ds-radius-lg);margin:1rem 0;border:1px solid var(--ds-color-border)}.article-layout{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:2rem;align-items:start;max-width:950px;margin:1rem auto}.article-body{font-size:1.02rem;line-height:2.15;color:var(--ds-color-text-primary);overflow-wrap:anywhere}.article-body :deep(h2){font-size:1.55rem;line-height:1.5;margin:2rem 0 .6rem}.article-body :deep(img){max-width:100%;height:auto;border-radius:12px}.article-body :deep(a){color:var(--ds-color-action-primary)}.article-body :deep(blockquote){margin:1.4rem 0;padding:.8rem 1rem;border-right:3px solid var(--ds-color-action-accent);background:var(--ds-color-surface-muted);border-radius:8px}.article-products{position:sticky;top:1rem;border:1px solid var(--ds-color-border);border-radius:var(--ds-radius-lg);padding:1rem;background:var(--ds-color-surface-raised)}.article-products h2{font-size:1rem;margin:0 0 .8rem}.article-product{display:flex;align-items:center;gap:.65rem;padding:.65rem 0;border-top:1px solid var(--ds-color-border);color:inherit;text-decoration:none}.article-product img,.product-placeholder{width:48px;height:48px;object-fit:cover;border-radius:10px;background:var(--ds-color-surface-muted);display:grid;place-items:center}.article-product>span:nth-child(2){display:grid;gap:.2rem;flex:1}.article-product b{font-size:.85rem}.article-product small{font-size:.73rem;color:var(--ds-color-text-secondary)}.article-product>svg{color:var(--ds-color-action-primary)}.article-state{text-align:center;padding:6rem 1rem;color:var(--ds-color-text-secondary)}.article-state a{display:block;margin-top:1rem;color:var(--ds-color-action-primary)}@media(max-width:760px){.article-layout{grid-template-columns:1fr}.article-products{position:static}.article-body{font-size:.96rem}}
</style>
